"""Polskie nazwy reprezentacji (ten sam słownik co w aplikacji)."""
PL = {
"Poland": "Polska",
"Germany": "Niemcy",
"Spain": "Hiszpania",
"France": "Francja",
"England": "Anglia",
"Italy": "Włochy",
"Netherlands": "Holandia",
"Belgium": "Belgia",
"Portugal": "Portugalia",
"Croatia": "Chorwacja",
"Czech Republic": "Czechy",
"Slovakia": "Słowacja",
"Ukraine": "Ukraina",
"Austria": "Austria",
"Switzerland": "Szwajcaria",
"Denmark": "Dania",
"Sweden": "Szwecja",
"Norway": "Norwegia",
"Finland": "Finlandia",
"Scotland": "Szkocja",
"Wales": "Walia",
"Republic of Ireland": "Irlandia",
"Northern Ireland": "Irlandia Północna",
"Hungary": "Węgry",
"Romania": "Rumunia",
"Serbia": "Serbia",
"Greece": "Grecja",
"Turkey": "Turcja",
"Albania": "Albania",
"Slovenia": "Słowenia",
"Bosnia and Herzegovina": "Bośnia i Hercegowina",
"Iceland": "Islandia",
"Lithuania": "Litwa",
"Latvia": "Łotwa",
"Estonia": "Estonia",
"Georgia": "Gruzja",
"Armenia": "Armenia",
"Bulgaria": "Bułgaria",
"North Macedonia": "Macedonia Północna",
"Montenegro": "Czarnogóra",
"Moldova": "Mołdawia",
"Belarus": "Białoruś",
"Kazakhstan": "Kazachstan",
"Brazil": "Brazylia",
"Argentina": "Argentyna",
"Mexico": "Meksyk",
"United States": "USA",
"Japan": "Japonia",
"South Korea": "Korea Płd.",
"Morocco": "Maroko",
"Colombia": "Kolumbia",
"Uruguay": "Urugwaj",
"Israel": "Izrael",
"Cyprus": "Cypr",
"Luxembourg": "Luksemburg",
"Malta": "Malta",
"Andorra": "Andora",
"San Marino": "San Marino",
"Kosovo": "Kosowo",
"Faroe Islands": "Wyspy Owcze",
"Gibraltar": "Gibraltar",
"Azerbaijan": "Azerbejdżan",
"Liechtenstein": "Liechtenstein",
"Canada": "Kanada",
"Australia": "Australia",
"Egypt": "Egipt",
"Senegal": "Senegal",
"Nigeria": "Nigeria",
"Tunisia": "Tunezja",
"Algeria": "Algieria",
"Iran": "Iran",
"Saudi Arabia": "Arabia Saudyjska",
"Bosnia & Herzegovina": "Bośnia i Hercegowina",
"Bosnia-Herzegovina": "Bośnia i Hercegowina",
"Czechia": "Czechy",
"Türkiye": "Turcja",
"Ireland": "Irlandia",
"Korea Republic": "Korea Płd.",
"USA": "USA",
"Ivory Coast": "Wybrzeże Kości Słoniowej"
}

def pl(n):
    return PL.get(n, n) if n else n

def pl_txt(s, *druzyny):
    """Zamienia angielskie nazwy drużyn w tekście na polskie (najpierw dłuższe, np. 'Northern Ireland' przed 'Ireland')."""
    o = str(s or '')
    for n in sorted([d for d in druzyny if d and d in PL], key=len, reverse=True):
        o = o.replace(n, PL[n])
    return o

def pl_mecz(m):
    return ' – '.join(pl(x) for x in str(m).split(' – '))
